In [2]:
import numpy as np 


In [ ]:
#this is 1d array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [7]:
#this is 2d array 
a = np.array([[1,2,3,4],[3,5,6,7]])
a

array([[1, 2, 3, 4],
       [3, 5, 6, 7]])

In [10]:
#this is 3d array 
a = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,1,4]]])
a

array([[[1, 2, 3],
        [4, 5, 6]],

       [[6, 7, 8],
        [9, 1, 4]]])

In [12]:
a = np.array([1,2,3] , dtype='float')
a

array([1., 2., 3.])

In [13]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [21]:
np.arange(1,21).reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [ ]:
np.ones((3,4)) #for interview question 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])