In [2]:
import numpy as np 


In [4]:
#this is 1d array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [5]:
#this is 2d array 
a = np.array([[1,2,3,4],[3,5,6,7]])
a

array([[1, 2, 3, 4],
       [3, 5, 6, 7]])

In [6]:
#this is 3d array 
a = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,1,4]]])
a

array([[[1, 2, 3],
        [4, 5, 6]],

       [[6, 7, 8],
        [9, 1, 4]]])

In [7]:
a = np.array([1,2,3] , dtype='float')
a

array([1., 2., 3.])

In [8]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [10]:
np.arange(1,21).reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [11]:
np.ones((3,4)) #for interview question 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.random.random((4,5))

array([[0.03038361, 0.74758267, 0.08145793, 0.33149081, 0.901558  ],
       [0.6460116 , 0.19703106, 0.74622207, 0.73385948, 0.40751659],
       [0.95402584, 0.01508942, 0.3179601 , 0.55114714, 0.91543718],
       [0.42521881, 0.8193855 , 0.80165406, 0.3556549 , 0.8042083 ]])

In [15]:
np.random.randint(1,100)

17

In [16]:
np.random.randint(1,100,20)

array([47, 21, 18, 69, 30, 47, 93, 19, 56,  5, 94, 35, 17, 29, 60,  6,  6,
       83, 94, 42])

In [ ]:
np.random.seed(32)
np.random.randint(1,20,5) 

array([12,  6,  8,  4,  6])

In [31]:
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [34]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [35]:
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [41]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a1 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Scaler Operation

In [43]:
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [44]:
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [45]:
a1>10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

## Vector Operation

In [46]:
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

## Functions

In [50]:
print(a2.min())
np.min(a2)

12


np.int64(12)

In [ ]:
a2.max()

np.int64(23)

In [52]:
np.max(a2)

np.int64(23)

In [ ]:
a2.argmax() #return the index value of highest number

np.int64(11)

In [ ]:
a2.argmin() #return the index value of minimum number

np.int64(0)

In [55]:
a2.sum()

np.int64(210)

In [ ]:
a2.min(axis=1) # 1 for row 

array([12, 16, 20])

In [59]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
a1.sum(axis=1)

array([ 6, 22, 38])

In [ ]:
a2.max(axis=0) # 0 for column

array([20, 21, 22, 23])

In [64]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [63]:
a2.prod(axis=1)

array([ 32760,  93024, 212520])

In [66]:
np.sin(a2)

array([[-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 ]])

In [9]:
a3 = np.arange(24,42).reshape(6,3)
a3

array([[24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41]])

In [12]:
a4 = np.arange(42,60).reshape(3,6)
a4

array([[42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [13]:
a3.dot(a4)

array([[3612, 3687, 3762, 3837, 3912, 3987],
       [4044, 4128, 4212, 4296, 4380, 4464],
       [4476, 4569, 4662, 4755, 4848, 4941],
       [4908, 5010, 5112, 5214, 5316, 5418],
       [5340, 5451, 5562, 5673, 5784, 5895],
       [5772, 5892, 6012, 6132, 6252, 6372]])

In [14]:
np.dot(a3,a4)

array([[3612, 3687, 3762, 3837, 3912, 3987],
       [4044, 4128, 4212, 4296, 4380, 4464],
       [4476, 4569, 4662, 4755, 4848, 4941],
       [4908, 5010, 5112, 5214, 5316, 5418],
       [5340, 5451, 5562, 5673, 5784, 5895],
       [5772, 5892, 6012, 6132, 6252, 6372]])

In [18]:
np.exp(a3)

array([[2.64891221e+10, 7.20048993e+10, 1.95729609e+11],
       [5.32048241e+11, 1.44625706e+12, 3.93133430e+12],
       [1.06864746e+13, 2.90488497e+13, 7.89629602e+13],
       [2.14643580e+14, 5.83461743e+14, 1.58601345e+15],
       [4.31123155e+15, 1.17191424e+16, 3.18559318e+16],
       [8.65934004e+16, 2.35385267e+17, 6.39843494e+17]])

In [19]:
np.log(a3)

array([[3.17805383, 3.21887582, 3.25809654],
       [3.29583687, 3.33220451, 3.36729583],
       [3.40119738, 3.4339872 , 3.4657359 ],
       [3.49650756, 3.52636052, 3.55534806],
       [3.58351894, 3.61091791, 3.63758616],
       [3.66356165, 3.68887945, 3.71357207]])

In [21]:
b = np.random.random((2,3))*100
b

array([[13.53653471, 49.18898121, 70.97688754],
       [14.38531351, 99.31126708, 28.98031781]])

In [22]:
np.floor(b)

array([[13., 49., 70.],
       [14., 99., 28.]])

In [23]:
np.ceil(b)

array([[ 14.,  50.,  71.],
       [ 15., 100.,  29.]])

In [24]:
np.round(b)

array([[14., 49., 71.],
       [14., 99., 29.]])

In [25]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [26]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a1[5]

np.int64(5)

In [28]:
a1[-1]

np.int64(9)

In [29]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
a2[1,2]

np.int64(6)

In [31]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [33]:
a3[1,1,1]

np.int64(7)

In [34]:
a1[2:5]

array([2, 3, 4])

In [35]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
a2[2:]

array([[ 8,  9, 10, 11]])

In [38]:
a2[2,1:3]

array([ 9, 10])

In [39]:
a2[:,3]

array([ 3,  7, 11])

In [40]:
a2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [41]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [43]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [45]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [48]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [49]:
for i in np.nditer(a3):
    print(i)


0
1
2
3
4
5
6
7


In [57]:
b1 = np.arange(12).reshape(3,4)
b2 = np.arange(12,24).reshape(3,4)
b2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [59]:
np.hstack((b1,b2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [60]:
np.vstack((b1,b2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [64]:
np.vsplit(b2,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [65]:
np.hsplit(b1,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]